= Kong

- https://docs.konghq.com/gateway/latest/get-started/[Kong Gateway -> Get Started]

.Get Kong for the Quick start
[source,bash]
----
curl -Ls https://get.konghq.com/quickstart | bash
----
Source: https://docs.konghq.com/gateway/3.2.x/get-started/

== Run Kong Gatway with podman

In the section https://podman.io/[Podman] is used to spin up the containers.

- https://docs.konghq.com/gateway/latest/install/docker/[Install Kong Gateway on Docker ]


.Set variables (config.conf)
[source,bash]
----
export PODMAN_KONG_NETWORK=kong-net

export POSTGRES_KONG_USER=kong
export POSTGRES_KONG_PASSWORD=playground
export POSTGRES_KONG_DB=kong
export POSTGRES_KONG_HOST=postgres-kong-playground

export KONG_GATEWAY_OSS_VERSION=3.2.2
----

Script: link:config.conf[config.conf]

TIP: Do not change the value of `POSTGRES_KONG_DB` from `kong`.

.We need a network
[source,bash]
----
source ./config.conf
podman network create $PODMAN_KONG_NETWORK
----

Script link:containers/create_network.sh[create_network.sh]

.Start Postgres database
[source,bash]
----
source ./config.conf
podman run -it \
    --rm=true \
    --name $POSTGRES_KONG_HOST \
    --network=$PODMAN_KONG_NETWORK \
    -e POSTGRES_USER=$POSTGRES_KONG_USER \
    -e POSTGRES_PASSWORD=$POSTGRES_KONG_PASSWORD \
    -e POSTGRES_DB=$POSTGRES_KONG_DB \
    -p 5442:5432 \
    postgres:15
----

Script: link:containers/start_postgres_for_kong.sh[start_postgres_for_kong.sh]

.Prepare the Kong Gateway OSS Postgres database
[source,bash]
----
source ./config.conf
podman run -it \
    --rm \
    --network=$PODMAN_KONG_NETWORK \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=$POSTGRES_KONG_HOST" \
    -e "KONG_PG_PASSWORD=$POSTGRES_KONG_PASSWORD" \
    kong:$KONG_GATEWAY_OSS_VERSION kong migrations bootstrap
----

Script: link:containers/prepare_kong_gatway_postgres.sh[prepare_kong_gatway_postgres.sh]

.Start Kong Gatway OSS with Postgres
[source,bash]
----
source ./config.conf
podman run -it \
    --rm \
    --name kong-gateway-oss \
    --network=$PODMAN_KONG_NETWORK \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=$POSTGRES_KONG_HOST" \
    -e "KONG_PG_USER=$POSTGRES_KONG_USER" \
    -e "KONG_PG_PASSWORD=$POSTGRES_KONG_PASSWORD" \
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
    -e "KONG_ADMIN_GUI_URL=http://localhost:8002, 0.0.0.0:8444 ssl" \
    -p 8000:8000 \
    -p 8443:8443 \
    -p 127.0.0.1:8001:8001 \
    -p 127.0.0.1:8444:8444 \
    kong:$KONG_GATEWAY_OSS_VERSION
----

Script: link:containers/start_kong_gatway_oss_with_postgres.sh[start_kong_gatway_oss_with_postgres.sh]

As Kong Gatway OSS is missing a GUI we go with https://pantsel.github.io/konga/[Konga]. Konga was last released on May 16, 2020 (v0.14.9)

.Start Konga
[source,bash]
----
source ./config.conf
podman run -it \
    --rm \
    --name konga \
    --network=$PODMAN_KONG_NETWORK \
    -e "TOKEN_SECRET=SuperSecret" \
    -p 1337:1337 \
    pantsel/konga
----

Script: link:containers/start_pansel_konga.sh[start_pansel_konga.sh]


== API calls to Kong Gatway

Subfolder for use of admin-api to update Kong Gatway link:admin-api[admin-api].

== Quarkus ToDo

A ToDo created with Quarkus using a Postgres database.

link::quarkus/quarkus-todo-app[quarkus/quarkus-todo-app]

.Start a container in kong-net network based on quarkus/todo-app
[source,bash]
----
podman run -it \
    --rm=true \
    --network=kong-net \
    --name=kong-quarkus-todo \
    -p 8180:8080 jarrydk/kong-quarkus-todo
----

== Spring ToDo

A ToDo created with Spring using a Postgres database.

link::spring/spring-todo-app[spring/spring-todo-app]

.Start container
[source,bash]
----
podman run -it \
    --rm=true \
    --network=kong-net \
    --name=kong-spring-todo \
    -e spring.datasource.url=jdbc:postgresql://postgres-spring-playground:5432/hibernate_db \
    -p 8280:8080 jarrydk/kong-spring-todo
----

== Create user and password in Postgres

[source,bash]
----
CREATE USER quarkus_todo_dev WITH PASSWORD 'playground';
CREATE DATABASE quarkus_todo_dev OWNER quarkus_todo_dev;
----

[source,bash]
----
CREATE USER spring_todo_dev WITH PASSWORD 'playground';
CREATE DATABASE spring_todo_dev OWNER spring_todo_dev;
----

[source,bash]
----
CREATE USER todo_dev WITH PASSWORD 'playground';
CREATE DATABASE todo_dev OWNER todo_dev;
----




== Links

- https://konghq.com/install[Install Kong Gateway]
- https://docs.konghq.com/gateway/latest/install/docker[Install Kong Gateway on Docker]
- https://docs.konghq.com/gateway/latest/install/linux/rhel[Install Kong Gateway on RHEL]

- https://konghq.com/blog/engineering/mutual-tls-api-gateway
- https://support.konghq.com/support/s/article/How-to-setup-Kong-to-serve-an-SSL-certificate-for-API-requests
- https://support.konghq.com/support/s/article/How-to-define-SSL-Certificates-and-where-you-can-use-them
- https://dev.to/rehmatworks/protecting-kong-api-gateway-using-let-s-encrypt-1id6

=== Admin API

- https://docs.konghq.com/gateway/latest/admin-api/#service-object
- https://docs.konghq.com/gateway/latest/admin-api/#route-object
- https://docs.konghq.com/gateway/latest/admin-api/#upstream-object