#!/bin/bash
source ./config.conf
podman run -dt \
    --rm \
    --name $KONG_GATEWAY_OSS_HOST \
    --network=$PODMAN_KONG_NETWORK \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=$POSTGRES_KONG_HOST" \
    -e "KONG_PG_USER=$POSTGRES_KONG_USER" \
    -e "KONG_PG_PASSWORD=$POSTGRES_KONG_PASSWORD" \
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_LISTEN=0.0.0.0:$KONG_GATEWAY_OSS_ADMIN_PORT, 0.0.0.0:$KONG_GATEWAY_OSS_ADMIN_TLS_PORT ssl" \
    -p $KONG_GATEWAY_OSS_PORT:8000 \
    -p $KONG_GATEWAY_OSS_TLS_PORT:8443 \
    -p 127.0.0.1:$KONG_GATEWAY_OSS_ADMIN_PORT:8001 \
    -p 127.0.0.1:$KONG_GATEWAY_OSS_ADMIN_TLS_PORT:8444 \
    kong:$KONG_GATEWAY_OSS_VERSION
